# Generated by Django 2.2.9 on 2020-03-18 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coronaApp', '0002_auto_20200318_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='maladie',
        ),
    ]
