# Generated by Django 2.2.9 on 2020-03-18 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coronaApp', '0003_remove_question_maladie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reponse',
            name='question',
        ),
    ]
