# Generated by Django 2.2.9 on 2020-03-25 20:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('coronaApp', '0006_auto_20200320_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeReponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('libelle', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='reponse',
            name='type_reponse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coronaApp.TypeReponse'),
        ),
    ]
