# Generated by Django 2.2.9 on 2020-03-25 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coronaApp', '0007_auto_20200325_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reponse',
            name='type_reponse',
        ),
        migrations.AddField(
            model_name='question',
            name='type_reponse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coronaApp.TypeReponse'),
        ),
    ]
