# Generated by Django 2.2.9 on 2020-03-27 23:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('coronaApp', '0008_auto_20200325_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptome',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('libelle', models.CharField(blank=True, help_text='le libelle symptome', max_length=255, null=True)),
                ('maladie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coronaApp.Maladie')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
