# Generated by Django 2.2.9 on 2020-03-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coronaApp', '0011_remove_question_type_reponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='numero',
            field=models.CharField(blank=True, help_text='Id du symptome auquel la question est liée.', max_length=255, null=True),
        ),
    ]
