# Generated by Django 2.2.9 on 2020-03-29 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coronaApp', '0012_auto_20200329_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptome',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coronaApp.Question'),
        ),
    ]
