# Generated by Django 2.2.9 on 2020-03-30 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coronaApp', '0013_symptome_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyse',
            name='classification',
        ),
    ]
