# Generated by Django 2.2.9 on 2020-03-31 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coronaApp', '0014_remove_analyse_classification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='classe',
        ),
        migrations.AddField(
            model_name='profile',
            name='maladie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coronaApp.Maladie'),
        ),
    ]
