# Generated by Django 2.2.9 on 2020-04-02 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coronaApp', '0017_analyse_classification'),
    ]

    operations = [
        migrations.AddField(
            model_name='reponseadittionnelle',
            name='analyse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coronaApp.Analyse'),
        ),
    ]
