# Generated by Django 2.2.9 on 2020-04-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coronaApp', '0018_reponseadittionnelle_analyse'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyse',
            name='score_corona',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='analyse',
            name='score_maladie',
            field=models.IntegerField(null=True),
        ),
    ]
