# Generated by Django 2.2.9 on 2020-04-08 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coronaApp', '0020_analyse_medecin'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyse',
            name='validation',
            field=models.IntegerField(null=True),
        ),
    ]
