# Generated by Django 2.2.9 on 2020-04-09 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coronaApp', '0022_auto_20200409_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyse',
            name='medecin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medecin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='validation',
            field=models.IntegerField(default=-1, null=True),
        ),
    ]
